// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Conexao direta (session mode, porta 5432) para migrations/introspeccao.
    // O runtime do app usa DATABASE_URL (pooler, 6543) ao instanciar PrismaClient.
    url: process.env["DIRECT_URL"],
  },
});
