// Dados iniciais do seed (antes ficavam como mock em lib/data, que agora le do
// Postgres). Fonte unica do `pnpm db:seed`. Precos em centavos.
import type { Order, Product } from "../lib/data/types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "booster-box-scarlet-tempest",
    name: "Booster Box — Scarlet Tempest",
    category: "Booster Box",
    sku: "BB-SCAR",
    priceCents: 68990,
    discountPct: 12,
    rating: 4.9,
    reviewCount: 142,
    stock: 18,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Mais vendido",
    imageUrl: "/products/placeholder.svg",
    description: "Caixa lacrada com 36 boosters da expansao Scarlet Tempest.",
    createdAt: "2025-09-02T12:00:00.000Z",
  },
  {
    id: "p-002",
    slug: "elite-trainer-box-obsidian-flames",
    name: "Elite Trainer Box — Obsidian Flames",
    category: "Elite Trainer Box",
    sku: "ETB-OBSF",
    priceCents: 28900,
    discountPct: 8,
    rating: 4.8,
    reviewCount: 88,
    stock: 24,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Novo",
    imageUrl: "/products/placeholder.svg",
    description: "ETB com boosters, dados, marcadores e baralho de energia.",
    createdAt: "2025-10-10T12:00:00.000Z",
  },
  {
    id: "p-003",
    slug: "booster-pack-paldea-evolved",
    name: "Booster Pack — Paldea Evolved",
    category: "Booster Pack",
    sku: "BP-PALD",
    priceCents: 4299,
    discountPct: 20,
    rating: 4.7,
    reviewCount: 412,
    stock: 142,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-20%",
    imageUrl: "/products/placeholder.svg",
    description: "Pacote avulso com cartas da expansao Paldea Evolved.",
    createdAt: "2025-06-21T12:00:00.000Z",
  },
  {
    id: "p-004",
    slug: "tin-collection-charizard-ex",
    name: "Tin Collection — Charizard ex",
    category: "Tin",
    sku: "TIN-CHAR",
    priceCents: 15990,
    discountPct: 0,
    rating: 4.9,
    reviewCount: 65,
    stock: 4,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Edição",
    imageUrl: "/products/placeholder.svg",
    description: "Lata colecionavel com carta promo de Charizard ex.",
    createdAt: "2025-08-05T12:00:00.000Z",
  },
  {
    id: "p-005",
    slug: "colecao-premium-mewtwo-vstar",
    name: "Coleção Premium — Mewtwo VSTAR",
    category: "Coleção Especial",
    sku: "CE-MEWT",
    priceCents: 44900,
    discountPct: 15,
    rating: 5.0,
    reviewCount: 31,
    stock: 0,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Premium",
    imageUrl: "/products/placeholder.svg",
    description: "Box premium com figure, boosters e carta foil de Mewtwo VSTAR.",
    createdAt: "2025-07-18T12:00:00.000Z",
  },
  {
    id: "p-006",
    slug: "sleeves-ultra-pro-100un-holo",
    name: "Sleeves Ultra Pro (100un) Holo",
    category: "Acessórios",
    sku: "ACC-SLV-UP",
    priceCents: 3990,
    discountPct: 5,
    rating: 4.6,
    reviewCount: 208,
    stock: 87,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Pacote com 100 protetores holograficos tamanho padrao.",
    createdAt: "2025-05-12T12:00:00.000Z",
  },
  {
    id: "p-007",
    slug: "booster-box-silver-tempest",
    name: "Booster Box — Silver Tempest",
    category: "Booster Box",
    sku: "BB-SILV",
    priceCents: 72990,
    discountPct: 18,
    rating: 4.8,
    reviewCount: 97,
    stock: 9,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-18%",
    imageUrl: "/products/placeholder.svg",
    description: "Caixa lacrada com 36 boosters da expansao Silver Tempest.",
    createdAt: "2025-09-28T12:00:00.000Z",
  },
  {
    id: "p-008",
    slug: "tin-collection-greninja-v",
    name: "Tin Collection — Greninja V",
    category: "Tin",
    sku: "TIN-GREN",
    priceCents: 13990,
    discountPct: 5,
    rating: 4.7,
    reviewCount: 54,
    stock: 14,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Lata colecionavel com carta promo de Greninja V.",
    createdAt: "2025-08-22T12:00:00.000Z",
  },
  {
    id: "p-009",
    slug: "deck-box-acrilico-premium",
    name: "Deck Box Acrílico Premium",
    category: "Acessórios",
    sku: "ACC-DECKB",
    priceCents: 7990,
    discountPct: 10,
    rating: 4.5,
    reviewCount: 73,
    stock: 32,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Porta-deck em acrilico transparente para ate 100 cartas.",
    createdAt: "2025-04-30T12:00:00.000Z",
  },
  {
    id: "p-010",
    slug: "single-pikachu-illustrator-reprint",
    name: "Single — Pikachu Illustrator Reprint",
    category: "Single Card",
    sku: "SC-PIKA",
    priceCents: 129000,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 12,
    stock: 2,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Raro",
    imageUrl: "/products/placeholder.svg",
    description: "Reimpressao colecionavel da icônica carta Pikachu Illustrator.",
    createdAt: "2025-11-03T12:00:00.000Z",
  },
  {
    id: "p-011",
    slug: "playmat-studio-aurora-eevee",
    name: "Playmat Studio Aurora — Eevee",
    category: "Acessórios",
    sku: "ACC-PMAT-AUR",
    priceCents: 10900,
    discountPct: 0,
    rating: 4.8,
    reviewCount: 38,
    stock: 3,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Tapete de jogo antiderrapante com arte exclusiva de Eevee.",
    createdAt: "2025-10-19T12:00:00.000Z",
  },
  {
    id: "p-012",
    slug: "booster-pack-lost-origin",
    name: "Booster Pack — Lost Origin",
    category: "Booster Pack",
    sku: "BP-LOST",
    priceCents: 3850,
    discountPct: 0,
    rating: 4.6,
    reviewCount: 189,
    stock: 56,
    isActive: false,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Pacote avulso com cartas da expansao Lost Origin.",
    createdAt: "2025-03-14T12:00:00.000Z",
  },
  {
    id: "p-013",
    slug: "booster-box-paradox-rift",
    name: "Booster Box — Paradox Rift",
    category: "Booster Box",
    sku: "BB-PARA",
    priceCents: 75900,
    discountPct: 10,
    rating: 4.9,
    reviewCount: 54,
    stock: 7,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-10%",
    imageUrl: "/products/placeholder.svg",
    description: "Caixa lacrada com 36 boosters da expansao Paradox Rift.",
    createdAt: "2025-12-01T12:00:00.000Z",
  },
  {
    id: "p-014",
    slug: "booster-box-crown-zenith",
    name: "Booster Box — Crown Zenith",
    category: "Booster Box",
    sku: "BB-CROWN",
    priceCents: 84900,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 122,
    stock: 11,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Top",
    imageUrl: "/products/placeholder.svg",
    description: "Caixa especial da expansao Crown Zenith com cartas Galarian Gallery.",
    createdAt: "2025-12-20T12:00:00.000Z",
  },
  {
    id: "p-015",
    slug: "elite-trainer-box-paldean-fates",
    name: "Elite Trainer Box — Paldean Fates",
    category: "Elite Trainer Box",
    sku: "ETB-PALDF",
    priceCents: 31900,
    discountPct: 12,
    rating: 4.9,
    reviewCount: 71,
    stock: 16,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-12%",
    imageUrl: "/products/placeholder.svg",
    description: "ETB de Paldean Fates com boosters e acessorios de treinador.",
    createdAt: "2026-01-09T12:00:00.000Z",
  },
  {
    id: "p-016",
    slug: "elite-trainer-box-151",
    name: "Elite Trainer Box — 151",
    category: "Elite Trainer Box",
    sku: "ETB-151",
    priceCents: 39900,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 201,
    stock: 28,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Cult",
    imageUrl: "/products/placeholder.svg",
    description: "ETB da expansao 151 com os Pokemon originais de Kanto.",
    createdAt: "2025-11-25T12:00:00.000Z",
  },
  {
    id: "p-017",
    slug: "booster-pack-astral-radiance",
    name: "Booster Pack — Astral Radiance",
    category: "Booster Pack",
    sku: "BP-ASTR",
    priceCents: 3690,
    discountPct: 15,
    rating: 4.6,
    reviewCount: 312,
    stock: 95,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-15%",
    imageUrl: "/products/placeholder.svg",
    description: "Pacote avulso com cartas da expansao Astral Radiance.",
    createdAt: "2025-05-30T12:00:00.000Z",
  },
  {
    id: "p-018",
    slug: "booster-pack-brilliant-stars",
    name: "Booster Pack — Brilliant Stars",
    category: "Booster Pack",
    sku: "BP-BRIL",
    priceCents: 3990,
    discountPct: 0,
    rating: 4.7,
    reviewCount: 144,
    stock: 60,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Pacote avulso com cartas da expansao Brilliant Stars.",
    createdAt: "2025-04-08T12:00:00.000Z",
  },
  {
    id: "p-019",
    slug: "tin-collection-lugia-v",
    name: "Tin Collection — Lugia V",
    category: "Tin",
    sku: "TIN-LUGIA",
    priceCents: 14990,
    discountPct: 0,
    rating: 4.8,
    reviewCount: 42,
    stock: 19,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Lata colecionavel com carta promo de Lugia V.",
    createdAt: "2025-07-02T12:00:00.000Z",
  },
  {
    id: "p-020",
    slug: "tin-collection-rayquaza-vmax",
    name: "Tin Collection — Rayquaza VMAX",
    category: "Tin",
    sku: "TIN-RAYQ",
    priceCents: 17990,
    discountPct: 8,
    rating: 4.9,
    reviewCount: 63,
    stock: 22,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-8%",
    imageUrl: "/products/placeholder.svg",
    description: "Lata colecionavel com carta promo de Rayquaza VMAX.",
    createdAt: "2025-08-14T12:00:00.000Z",
  },
  {
    id: "p-021",
    slug: "single-charizard-vmax-rainbow",
    name: "Single — Charizard VMAX Rainbow",
    category: "Single Card",
    sku: "SC-CHAR-VMAX",
    priceCents: 289000,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 8,
    stock: 1,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Lendário",
    imageUrl: "/products/placeholder.svg",
    description: "Carta avulsa Charizard VMAX em raridade rainbow secret.",
    createdAt: "2025-12-11T12:00:00.000Z",
  },
  {
    id: "p-022",
    slug: "single-umbreon-vmax-alt-art",
    name: "Single — Umbreon VMAX Alt Art",
    category: "Single Card",
    sku: "SC-UMBR-ALT",
    priceCents: 429000,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 5,
    stock: 1,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Grail",
    imageUrl: "/products/placeholder.svg",
    description: "Carta avulsa Umbreon VMAX alternate art (Moonbreon).",
    createdAt: "2026-01-22T12:00:00.000Z",
  },
  {
    id: "p-023",
    slug: "single-lugia-v-alt-art",
    name: "Single — Lugia V Alt Art",
    category: "Single Card",
    sku: "SC-LUGIA-ALT",
    priceCents: 189000,
    discountPct: 0,
    rating: 5.0,
    reviewCount: 9,
    stock: 2,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Alt Art",
    imageUrl: "/products/placeholder.svg",
    description: "Carta avulsa Lugia V em arte alternativa de Silver Tempest.",
    createdAt: "2025-10-01T12:00:00.000Z",
  },
  {
    id: "p-024",
    slug: "sleeves-dragon-shield-matte-100un",
    name: "Sleeves Dragon Shield Matte (100un)",
    category: "Acessórios",
    sku: "ACC-SLV-DS",
    priceCents: 5490,
    discountPct: 0,
    rating: 4.7,
    reviewCount: 178,
    stock: 130,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Pacote com 100 protetores matte premium Dragon Shield.",
    createdAt: "2025-06-05T12:00:00.000Z",
  },
  {
    id: "p-025",
    slug: "binder-9-pocket-ziper-premium",
    name: "Binder 9-Pocket Zíper Premium",
    category: "Acessórios",
    sku: "ACC-BINDER9",
    priceCents: 18900,
    discountPct: 10,
    rating: 4.8,
    reviewCount: 96,
    stock: 12,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-10%",
    imageUrl: "/products/placeholder.svg",
    description: "Album com fecho ziper e 9 bolsos por pagina para 360 cartas.",
    createdAt: "2025-09-15T12:00:00.000Z",
  },
  {
    id: "p-026",
    slug: "colecao-premium-tapu-koko-gx",
    name: "Coleção Premium — Tapu Koko GX",
    category: "Coleção Especial",
    sku: "CE-TAPU",
    priceCents: 38900,
    discountPct: 0,
    rating: 4.8,
    reviewCount: 22,
    stock: 8,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: null,
    imageUrl: "/products/placeholder.svg",
    description: "Box especial com figure e boosters de Tapu Koko GX.",
    createdAt: "2025-07-27T12:00:00.000Z",
  },
  {
    id: "p-027",
    slug: "colecao-premium-zacian-v",
    name: "Coleção Premium — Zacian V",
    category: "Coleção Especial",
    sku: "CE-ZACIAN",
    priceCents: 41900,
    discountPct: 5,
    rating: 4.9,
    reviewCount: 18,
    stock: 6,
    isActive: true,
    isCarousel: false,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "-5%",
    imageUrl: "/products/placeholder.svg",
    description: "Box especial com figure e boosters de Zacian V.",
    createdAt: "2025-11-12T12:00:00.000Z",
  },
  {
    id: "p-028",
    slug: "playmat-premium-pikachu-holo",
    name: "Playmat Premium — Pikachu Holo",
    category: "Acessórios",
    sku: "ACC-PMAT-PIKA",
    priceCents: 13900,
    discountPct: 0,
    rating: 4.9,
    reviewCount: 54,
    stock: 25,
    isActive: true,
    isCarousel: true,
    weightGrams: 0,
    lengthCm: 0,
    widthCm: 0,
    heightCm: 0,
    badge: "Novo",
    imageUrl: "/products/placeholder.svg",
    description: "Tapete de jogo premium com acabamento holografico de Pikachu.",
    createdAt: "2026-01-30T12:00:00.000Z",
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: "#10421",
    userId: "user_mock_01",
    customerName: "João Silva Pereira",
    customerEmail: "joao.silva@email.com",
    customerPhone: "(41) 99876-5432",
    address: {
      cep: "80000-100",
      street: "Rua das Laranjeiras, 123",
      city: "Curitiba",
      state: "PR",
    },
    items: [
      {
        productId: "p-002",
        productName: "Elite Trainer Box — Obsidian Flames",
        quantity: 1,
        unitPriceCents: 26588,
      },
      {
        productId: "p-006",
        productName: "Sleeves Ultra Pro (100un) Holo",
        quantity: 1,
        unitPriceCents: 3791,
      },
    ],
    subtotalCents: 30379,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 0,
    totalCents: 30379,
    shippingService: null,
    shippingDays: null,
    paymentStatus: "paid",
    paymentMethod: "PIX",
    shippingStatus: "pending",
    internalNote: null,
    createdAt: "2026-05-20T18:22:00.000Z",
  },
  {
    id: "#10420",
    userId: "user_mock_02",
    customerName: "Mariana Costa",
    customerEmail: "mariana.c@email.com",
    customerPhone: "(11) 98123-4567",
    address: {
      cep: "04567-010",
      street: "Av. Paulista, 1500, ap 82",
      city: "São Paulo",
      state: "SP",
    },
    items: [
      {
        productId: "p-001",
        productName: "Booster Box — Scarlet Tempest",
        quantity: 1,
        unitPriceCents: 60711,
      },
    ],
    subtotalCents: 60711,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 3250,
    totalCents: 63961,
    shippingService: "Sedex",
    shippingDays: "3-5 dias",
    paymentStatus: "paid",
    paymentMethod: "Cartão 3x",
    shippingStatus: "sent",
    internalNote: null,
    createdAt: "2026-05-20T11:05:00.000Z",
  },
  {
    id: "#10419",
    userId: "user_mock_03",
    customerName: "Lucas Almeida",
    customerEmail: "lucas.a@gmail.com",
    customerPhone: "(31) 99654-3210",
    address: {
      cep: "30130-001",
      street: "Rua da Bahia, 488",
      city: "Belo Horizonte",
      state: "MG",
    },
    items: [
      {
        productId: "p-004",
        productName: "Tin Collection — Charizard ex",
        quantity: 1,
        unitPriceCents: 15990,
      },
    ],
    subtotalCents: 15990,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 0,
    totalCents: 15990,
    shippingService: null,
    shippingDays: null,
    paymentStatus: "pending",
    paymentMethod: "Boleto",
    shippingStatus: "pending",
    internalNote: "Cliente pediu para segurar o envio ate sexta-feira.",
    createdAt: "2026-05-19T09:50:00.000Z",
  },
  {
    id: "#10418",
    userId: "user_mock_04",
    customerName: "Fernanda Rocha",
    customerEmail: "fer.rocha@email.com",
    customerPhone: "(21) 99432-1100",
    address: {
      cep: "22240-000",
      street: "Rua Voluntários, 230",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    items: [
      {
        productId: "p-001",
        productName: "Booster Box — Scarlet Tempest",
        quantity: 1,
        unitPriceCents: 60711,
      },
      {
        productId: "p-002",
        productName: "Elite Trainer Box — Obsidian Flames",
        quantity: 2,
        unitPriceCents: 26588,
      },
      {
        productId: "p-003",
        productName: "Booster Pack — Paldea Evolved",
        quantity: 5,
        unitPriceCents: 3439,
      },
    ],
    subtotalCents: 131082,
    discountCents: 10000,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 4890,
    totalCents: 125972,
    shippingService: "PAC",
    shippingDays: "7-9 dias",
    paymentStatus: "paid",
    paymentMethod: "PIX",
    shippingStatus: "pending",
    internalNote: null,
    createdAt: "2026-05-19T15:40:00.000Z",
  },
  {
    id: "#10417",
    userId: "user_mock_05",
    customerName: "Pedro Henrique Lima",
    customerEmail: "p.lima@email.com",
    customerPhone: "(48) 99123-7788",
    address: {
      cep: "88010-100",
      street: "Rua Felipe Schmidt, 50",
      city: "Florianópolis",
      state: "SC",
    },
    items: [
      {
        productId: "p-009",
        productName: "Deck Box Acrílico Premium",
        quantity: 1,
        unitPriceCents: 7191,
      },
    ],
    subtotalCents: 7191,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 2840,
    totalCents: 10031,
    shippingService: "Sedex",
    shippingDays: "4-6 dias",
    paymentStatus: "paid",
    paymentMethod: "PIX",
    shippingStatus: "delivered",
    internalNote: null,
    createdAt: "2026-05-18T16:12:00.000Z",
  },
  {
    id: "#10416",
    userId: "user_mock_06",
    customerName: "Ana Beatriz Souza",
    customerEmail: "ana.b@email.com",
    customerPhone: "(51) 99887-4422",
    address: {
      cep: "90420-070",
      street: "Av. Independência, 1010",
      city: "Porto Alegre",
      state: "RS",
    },
    items: [
      {
        productId: "p-005",
        productName: "Coleção Premium — Mewtwo VSTAR",
        quantity: 1,
        unitPriceCents: 38165,
      },
    ],
    subtotalCents: 38165,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 0,
    totalCents: 38165,
    shippingService: null,
    shippingDays: null,
    paymentStatus: "cancelled",
    paymentMethod: "Cartão",
    shippingStatus: "cancelled",
    internalNote: "Pagamento recusado pela operadora; pedido cancelado.",
    createdAt: "2026-05-18T10:30:00.000Z",
  },
  {
    id: "#10415",
    userId: "user_mock_07",
    customerName: "Rafael Tanaka",
    customerEmail: "r.tanaka@email.com",
    customerPhone: "(11) 99111-2244",
    address: {
      cep: "01310-100",
      street: "Av. Paulista, 2000",
      city: "São Paulo",
      state: "SP",
    },
    items: [
      {
        productId: "p-003",
        productName: "Booster Pack — Paldea Evolved",
        quantity: 4,
        unitPriceCents: 3439,
      },
    ],
    subtotalCents: 13756,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 1890,
    totalCents: 15646,
    shippingService: "Loggi",
    shippingDays: "2-3 dias",
    paymentStatus: "paid",
    paymentMethod: "PIX",
    shippingStatus: "sent",
    internalNote: null,
    createdAt: "2026-05-17T19:02:00.000Z",
  },
  {
    id: "#10414",
    userId: "user_mock_08",
    customerName: "Camila Ferreira",
    customerEmail: "c.ferreira@email.com",
    customerPhone: "(85) 99765-1100",
    address: {
      cep: "60165-090",
      street: "Av. Beira Mar, 300",
      city: "Fortaleza",
      state: "CE",
    },
    items: [
      {
        productId: "p-007",
        productName: "Booster Box — Silver Tempest",
        quantity: 1,
        unitPriceCents: 59852,
      },
    ],
    subtotalCents: 59852,
    discountCents: 0,
    couponCode: null,
    couponDiscountCents: 0,
    shippingCents: 0,
    totalCents: 59852,
    shippingService: null,
    shippingDays: null,
    paymentStatus: "paid",
    paymentMethod: "Cartão 6x",
    shippingStatus: "pending",
    internalNote: null,
    createdAt: "2026-05-17T13:18:00.000Z",
  },
];
